name: Process CSV and Excel Files with PostgreSQL

on:
  push:
    paths:
      - 'pcos_data/*.csv'
      - 'pcos_data/*.xlsx'

jobs:
  run-sql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  
    - name: Install PostgreSQL Client Tools
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql-client-16

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl sqlalchemy psycopg2-binary

    - name: Process CSV and Excel files
      run: python create_tables.py

    - name: Export database to SQL file
      run: |
        pg_dump -h localhost -p 5432 -U user -d mydatabase -f pcos_data/mydatabase.sql
      env:
        PGPASSWORD: password

    - name: Save processed data
      uses: actions/upload-artifact@v4
      with:
        name: processeddata
        path: pcos_data/mydatabase.sql
  
volumes:
  postgres-data:
