name: Create SQL Tables from Files

on:
  push:
    #paths:
    #  - 'pcos_data/*.csv'
    #  - 'pcos_data/*.xlsx'
  pull_request:
  workflow_dispatch:

jobs:
  create_tables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy openpyxl

    - name: Create SQL tables
      run: python pcos_data/create_tables.py
      env:
        DB_URL: ${{ secrets.DB_URL }}
