name: Create SQL Tables from Files

on:
  push:
    #paths:
    #  - 'pcos_data/*.csv'
    #  - 'pcos_data/*.xlsx'
  pull_request:
  workflow_dispatch:
  
jobs:
  create_tables:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy openpyxl psycopg2-binary  # Use psycopg2-binary for PostgreSQL

    - name: Create SQL tables
      working-directory: pcos  # Set the working directory to the root of the repository
      run: python pcos_data/create_tables.py  # Adjust path to create_tables.py as per your repository structure
      env:
        DB_URL: ${{ secrets.DB_URL }}
