name: Query PostgreSQL Tables

on:
  workflow_dispatch:

jobs:
  query-sql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: pcos_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PostgreSQL Client Tools
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql-client-16

    - name: Restore PostgreSQL database
      run: |
        psql -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }} -d pcos_db < pcos_db.sql
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy psycopg2-binary

    - name: Execute Python script
      run: python query_postgres.py

    - name: Show script output
      run: cat pcos_data/output.txt
      if: always()
