name: Execute PostgreSQL Queries

on:
  workflow_dispatch:
  
jobs:
  setup-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: pcos_db
        ports:
          - "5432:5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client Tools
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-16

      - name: Load SQL Dump into PostgreSQL
        run: |
          psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d pcos_db -f pcos_db.sql
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  run-sql:
    needs: setup-db
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client

      - name: Execute PostgreSQL Queries
        run: |
          psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d pcos_db -f queries.sql > query_output.txt
          cat query_output.txt
        shell: bash
