name: Execute Python Script and Show Output

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Enter the run ID of the first workflow'
        required: true

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download processed data
      uses: actions/download-artifact@v4
      with:
        name: processed-data
        path: pcos_data/processed-data
        repository: tina-m-dev/pcos
        run-id: ${{ github.event.inputs.run-id }}

    - name: List files in pcos_data (debugging)
      run: ls -R pcos_data

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy psycopg2-binary

    - name: Execute Python script
      run: python query_postgres.py

    - name: Show script output
      run: cat pcos_data/output.txt
      if: always()
