name: Execute SQL

on:
  workflow_dispatch:
  
jobs:
  run-sql:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: pcos_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PostgreSQL queries and capture output
        run: |
          psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d pcos_db -f queries.sql > query_output.txt
          cat query_output.txt
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
