name: Initialize PostgreSQL Database

on:
  workflow_dispatch:

jobs:
  setup-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: pcos_db
        ports:
          - "5432:5432"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get install postgresql-client

      - name: Load SQL Dump into PostgreSQL
        run: |
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -U ${{ secrets.POSTGRES_USER }} -d pcos_db -f pcos_db.sql
