name: Run SQL Script

on: [push, pull_request]

jobs:
  run-sql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for PostgreSQL to be ready
      run: |
        while ! pg_isready -h localhost -p 5432 > /dev/null 2> /dev/null; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Run SQL script
      env:
        PGPASSWORD: password
      run: psql -h localhost -U user -d mydatabase -f your_script.sql
