name: Run SQL Script

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for PostgreSQL to be ready
      run: |
        while ! pg_isready -h localhost -p 5432 > /dev/null 2> /dev/null; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Create table for CSV data
      env:
        PGPASSWORD: password
      run: psql -h localhost -U user -d mydatabase -f create_table.sql

    - name: Import CSV into PostgreSQL
      env:
        PGPASSWORD: password
      run: |
        psql -h localhost -U user -d mydatabase -c "\copy pcos_infertility FROM 'PCOS_infertility.csv' CSV HEADER"

    - name: Verify table creation
      env:
        PGPASSWORD: password
      run: |
        echo "Listing tables in the database:"
        psql -h localhost -U user -d mydatabase -c "\dt"
        echo "Displaying contents of the table:"
        psql -h localhost -U user -d mydatabase -c "SELECT * FROM pcos_infertility;"
